services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/armv7-homeassistant"
    volumes:
      - /PATH_TO_YOUR_CONFIG:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    device: /dev/ttyACM0:/dev/ttyUSB0
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      TZ: Europe/Warsaw
